feat(packages): add search and user onboarding
sourcefuse/arc-ng-components pull request #2
Opened 2023-09-18 11:52 UTC by Surbhi-sharma1

add search and user onboarding libraries.
add sandbox examples 

GH-1

## Description

-add search and user onboarding in packages
- add sandbox examples

Fixes #1 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-18 13:49 UTC, yeshamavani commented on .github/workflows/combine-prs.yml
is this file needed here ?

2023-09-18 13:49 UTC, yeshamavani commented on packages/search/CHANGELOG.md
> +* fix(search-client): increase width of search dropdown and add ellipsis on overflow (#392) ([4d2f0af](https://github.com/sourcefuse/loopback4-microservice-catalog/commit/4d2f0af)), closes [#392](htt
refernce to catalog

2023-09-18 13:49 UTC, yeshamavani commented on packages/search/projects/search-lib/CHANGELOG.md
> +* feat(user-onboarding): add element support and script for building (#1377) ([eebbe4e](https://github.com/sourcefuse/loopback4-microservice-catalog/commit/eebbe4e)), closes [#1377](https://github.co
user-onboarding ???

2023-09-18 13:49 UTC, yeshamavani commented on packages/user-onboarding/CHANGELOG.md
> +* refactor(core): publishing user onboarding (#380) ([ecaf4c2](https://github.com/sourcefuse/loopback4-microservice-catalog/commit/ecaf4c2)), closes [#380](https://github.com/sourcefuse/loopback4-mic
same

2023-09-19 07:44 UTC, Surbhi-sharma1 commented on .github/workflows/combine-prs.yml
Removed

2023-09-19 07:44 UTC, Surbhi-sharma1 commented on packages/search/CHANGELOG.md
> +* fix(search-client): increase width of search dropdown and add ellipsis on overflow (#392) ([4d2f0af](https://github.com/sourcefuse/loopback4-microservice-catalog/commit/4d2f0af)), closes [#392](htt
Done with all the changes

2023-09-21 17:17 UTC, yeshamavani requested changes

2023-09-21 17:17 UTC, yeshamavani commented on packages/user-onboarding/package.json
> +    "url": "https://github.com/sourcefuse/loopback4-microservice-catalog.git",
reference to catalog

2023-09-21 17:17 UTC, yeshamavani commented on packages/user-onboarding/projects/user-onboarding-element/CHANGELOG.md
delete this file

2023-09-21 17:17 UTC, yeshamavani commented on packages/user-onboarding/projects/user-onboarding-lib/CHANGELOG.md
delete

2023-09-21 17:17 UTC, yeshamavani commented on packages/user-onboarding/projects/user-onboarding-lib/package.json
> +    "url": "https://github.com/sourcefuse/loopback4-microservice-catalog.git",
same

2023-09-21 17:49 UTC, yeshamavani commented
also move the sandbox examples here

2023-09-22 08:55 UTC, Surbhi-sharma1 commented on packages/search/projects/search-lib/CHANGELOG.md
> +* feat(user-onboarding): add element support and script for building (#1377) ([eebbe4e](https://github.com/sourcefuse/loopback4-microservice-catalog/commit/eebbe4e)), closes [#1377](https://github.co
removed

2023-09-22 08:55 UTC, Surbhi-sharma1 commented on packages/user-onboarding/CHANGELOG.md
> +* refactor(core): publishing user onboarding (#380) ([ecaf4c2](https://github.com/sourcefuse/loopback4-microservice-catalog/commit/ecaf4c2)), closes [#380](https://github.com/sourcefuse/loopback4-mic
removed

2023-09-22 08:56 UTC, Surbhi-sharma1 commented on .github/workflows/docs.yml
removed

2023-09-22 08:56 UTC, Surbhi-sharma1 commented on .github/workflows/release.yml
> +          node-version: '18.x'
changed to 20.

2023-09-22 10:34 UTC, Surbhi-sharma1 commented on packages/search/projects/search-element/package.json
> +    "url": "https://github.com/sourcefuse/loopback4-microservice-catalog.git",
Done

2023-09-25 16:27 UTC, yeshamavani commented on .github/workflows/pull_request.yml
why did we remove this?

2023-09-25 16:28 UTC, yeshamavani commented on .github/workflows/release.yml
> +          node-version: '18.x'
file deleted?

2023-09-26 06:03 UTC, closed without merging