feat(ai-assistant): add ai-assistant library
sourcefuse/arc-ng-components pull request #21
Opened 2024-10-10 12:27 UTC by abhinavverma-sf

add ai-assistant-library

RPMS-37315

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2025-03-10 09:10 UTC, yeshamavani commented
@Deepika516 please you also review this PR

2025-03-12 11:28 UTC, Anurag-AD approved these changes

2025-03-12 11:29 UTC, nareshkharola123 approved these changes

2025-03-13 06:54 UTC, yeshamavani requested changes
make sure to make changes in both readme

2025-03-13 06:54 UTC, yeshamavani commented on packages/ai-assistant/README.md
> +npm install @sourceloop/ai-assistant
npm install @sourceloop/ai-assistant-client

2025-03-13 06:54 UTC, yeshamavani commented on packages/ai-assistant/README.md
> +projects/ai-assistant-lib/dist/sourceloop-ai-assistant-0.0.1.tgz
no need to add the tar process here 
this is not how we intent the users to use it

2025-03-13 06:54 UTC, yeshamavani commented on packages/ai-assistant/README.md
> +
no reference of tar anywhere 
the sandbox will also be updated to use the published libarary

2025-03-13 07:48 UTC, adarsh-sourcefuse commented on packages/ai-assistant/README.md
> +
done

2025-03-13 07:48 UTC, adarsh-sourcefuse commented on packages/ai-assistant/README.md
> +projects/ai-assistant-lib/dist/sourceloop-ai-assistant-0.0.1.tgz
done

2025-03-13 07:48 UTC, adarsh-sourcefuse commented on packages/ai-assistant/README.md
> +npm install @sourceloop/ai-assistant
done

2025-03-13 07:50 UTC, yeshamavani approved these changes

2025-03-13 07:50 UTC, merged