feat(sandbox): add ai-assistant sandbox example
sourcefuse/arc-ng-components pull request #22
Opened 2024-10-10 12:33 UTC by abhinavverma-sf

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2025-02-28 10:42 UTC, yeshamavani requested changes

2025-02-28 10:42 UTC, yeshamavani commented on packages/ai-assistant/README.md
please update this 
helping user to understand how to utilise this

2025-02-28 10:42 UTC, yeshamavani commented on packages/ai-assistant/package.json
> +  "private": false,
compare with other library 
the outer and inner package.json files are different

2025-02-28 10:42 UTC, yeshamavani commented on packages/ai-assistant/package.json
> +    "directory": "packages/user-onboarding"
wrong folder name

2025-02-28 10:42 UTC, yeshamavani commented on packages/ai-assistant/projects/ai-assistant-lib/README.md
update readme file

2025-02-28 10:43 UTC, yeshamavani commented
CI checks failing

2025-03-04 03:45 UTC, adarsh-sourcefuse commented on packages/ai-assistant/README.md
done

2025-03-04 03:45 UTC, adarsh-sourcefuse commented on packages/ai-assistant/package.json
> +  "private": false,
done

2025-03-04 03:45 UTC, adarsh-sourcefuse commented on packages/ai-assistant/package.json
> +    "directory": "packages/user-onboarding"
done

2025-03-04 03:45 UTC, adarsh-sourcefuse commented on packages/ai-assistant/projects/ai-assistant-lib/README.md
done

2025-03-04 03:45 UTC, adarsh-sourcefuse commented on packages/ai-assistant/projects/ai-assistant-lib/ng-package.json
> +  "dest": "../../dist/ai-assistant",
done

2025-03-04 03:45 UTC, adarsh-sourcefuse commented on packages/ai-assistant/projects/ai-assistant-lib/package.json
done

2025-03-10 05:40 UTC, Deepika516 commented on packages/ai-assistant/package.json
> +    "lint": "ng lint",
we don't use `ng lint`. 
we use ` "lint": "eslint ./projects/**/*.ts",
               "lint:fix": "npm run lint -- --fix",`

2025-03-10 11:32 UTC, Deepika516 commented on packages/ai-assistant/README.md
Could you please provide a more detailed explanation of this README?

2025-03-11 05:34 UTC, nareshkharola123 commented on packages/ai-assistant/projects/ai-assistant-lib/src/lib/components/co-pilot-related-topics/co-pilot-related-topics.component.ts
> +// import {environment} from '@rao/env/environment';
cant we remove this

2025-03-11 05:34 UTC, nareshkharola123 commented on packages/ai-assistant/projects/ai-assistant-lib/src/lib/components/co-pilot-related-topics/co-pilot-related-topics.component.ts
> +        // );
same here

2025-03-11 12:42 UTC, adarsh-sourcefuse commented on packages/ai-assistant/projects/ai-assistant-lib/src/lib/components/co-pilot-related-topics/co-pilot-related-topics.component.ts
> +        // );
removed

2025-03-11 12:43 UTC, adarsh-sourcefuse commented on packages/ai-assistant/package.json
> +    "lint": "ng lint",
as discusses with @yeshamavani it will remaine same as other components

2025-03-11 12:45 UTC, nareshkharola123 approved these changes

2025-03-11 14:13 UTC, Deepika516 commented on packages/ai-assistant/package.json
> +    "lint": "ng lint",
ok

2025-03-11 14:41 UTC, Deepika516 approved these changes

2025-03-13 10:53 UTC, yeshamavani approved these changes

2025-03-13 10:56 UTC, merged